import {
  Loader2,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  X,
  Loader,
  Baseline,
  Bold,
  Italic,
  Underline,
  Type,
  PaintBucket,
  Image,
  Ellipsis,
  Highlighter,
  Ban,
  Plus,
  Link2,
  List,
  ListOrdered,
  AlignCenter,
  AlignLeft,
  AlignRight,
  AlignJustify,
  TriangleRight,
  Strikethrough,
  ALargeSmall,
  AlignStartVertical,
  AlignEndHorizontal,
  AlignCenterVertical,
  AlignCenterHorizontal,
  AlignStartHorizontal,
  AlignEndVertical,
  MousePointer2,
  Hand,
  Wand,
  Play,
  Trash2,
  Copy,
  Check,
  LifeBuoy,
  Upload,
  Lightbulb,
  ListTodo,
} from "lucide-react";

export const Icons = {
  todo: ListTodo,
  lightbulb: Lightbulb,
  upload: Upload,
  lifeBuoy: LifeBuoy,
  check: Check,
  copy: Copy,
  trash: Trash2,
  play: Play,
  wand: Wand,
  hand: Hand,
  cursor: MousePointer2,
  text: Type,
  alignEndVertical: AlignEndVertical,
  alignStartHorizontal: AlignStartHorizontal,
  alignCenterHorizontal: AlignCenterHorizontal,
  alignEndHorizontal: AlignEndHorizontal,
  alignStartVertical: AlignStartVertical,
  alignCenterVertical: AlignCenterVertical,
  textSize: ALargeSmall,
  strike: Strikethrough,
  triangleRight: TriangleRight,
  alignCenter: AlignCenter,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  alignJustify: AlignJustify,
  orderedList: ListOrdered,
  bulletList: List,
  link: Link2,
  add: Plus,
  Ban: Ban,
  highlighter: Highlighter,
  ellipsis: Ellipsis,
  image: Image,
  paintBucket: PaintBucket,
  type: Type,
  underline: Underline,
  Italic: Italic,
  bold: Bold,
  textColor: Baseline,
  close: X,
  spinner: Loader2,
  loader: Loader,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
};
